$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json 
name: ffmodel-compute-cluster
type: amlcompute
size: STANDARD_DS3_v2
min_instances: 0
max_instances: 1
idle_time_before_scale_down: 120
identity: # A managed identity is needed to read secrets from KV
  type: system_assigned
